name: Notify on Workflow Failure

onnn:
  workflow_run:
    workflows: ["Deploy React To GitHub Pages"]
    types:
      - completed

jobs:
  notify_failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification (Workflow Failure)
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS=${{ github.event.workflow_run.conclusion }}
          WORKFLOW_NAME=${{ github.event.workflow_run.name }}
          REPO=${{ github.repository }}
          JOB="Workflow Failure"

          if [ "$STATUS" == "success" ]; then
            COLOR="#36a64f"
            EMOJI="✅"
          elif [ "$STATUS" == "failure" ]; then
            COLOR="#ff0000"
            EMOJI="❌"
          else
            COLOR="#ffcc00"
            EMOJI="⚠️"
          fi

          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "'"$COLOR"'",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Workflow:* '"$WORKFLOW_NAME"'\n*Job:* '"$JOB"'\n*Status:* '"$EMOJI"' '"$STATUS"'"
                    }
                  },
                  {
                    "type": "context",
                    "elements": [
                      {
                        "type": "mrkdwn",
                        "text": "Repository: <https://github.com/'"$REPO"'|'"$REPO"'>"
                      }
                    ]
                  }
                ]
              }
            ]
          }' $SLACK_WEBHOOK
