deploy:
  needs: build
  runs-on: ubuntu-latest
  permissions:
    id-token: write 
    contents: read
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: deploy-package
        path: .

    - name: Extract TAR File
      run: tar -xvf all_files.tar

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::842675994865:role/github-aws-oicd
        aws-region: us-east-1 

    - name: Upload to S3
      run: aws s3 cp all_files.tar s3://my-deploy-bucket-003/deploy_package.tar

    - name: Trigger AWS CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name GitHubAction-app \
          --deployment-group-name GitHubAction-app-dg \
          --s3-location bucket=my-deploy-bucket-003,key=deploy_package.tar,bundleType=tar

    # Final step: Slack notification for job completion
    - name: Send Slack Notification (Deploy Complete)
      if: always() # Ensures this step runs regardless of success or failure
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: bash .github/scripts/slack_notify.sh "${{ job.status }}" "${{ github.ref_name }}" "${{ github.sha }}" "${{ github.repository }}" "Deploy Job Completed"
